import React from 'react'
import { ScrollText, Shield } from 'lucide-react'
import { TermsBackLink } from './TermsBackLink'

// ─── Section data ───────────────────────────────────────────────────────────

const SECTION_A = [
  {
    title: '1. Nature of the Experience',
    body: "The Gambit is a high-pressure, simulation-based experience designed to evaluate decision-making, problem-solving, and entrepreneurial thinking under time and situational constraints. This is not a standardized psychometric, academic, or clinical assessment.",
  },
  {
    title: '2. Voluntary Participation',
    body: 'Participation is voluntary. You may withdraw at any time; however, incomplete participation may affect your report.',
  },
  {
    title: '3. Developmental Purpose Only',
    body: 'This experience is intended solely for learning, reflection, and development. It is not a measure of intelligence, personality, mental health, or professional capability.',
  },
  {
    title: '4. Observation, Recording & Data Collection',
    body: 'During the session:',
    list: [
      'Your responses, decisions, and interactions will be observed and documented.',
      'Sessions may be audio/video recorded for internal review and program improvement.',
      'Recordings will remain confidential and will not be publicly shared without explicit consent.',
    ],
  },
  {
    title: '5. Report Sharing & Visibility',
    body: 'If your participation is part of a school, college, or corporate program:',
    list: [
      'Your report may be shared with authorized stakeholders (such as faculty, sponsors, or management).',
      'These stakeholders may have access to your participation details, decision-making approach, and performance within the simulation.',
    ],
    footer:
      'Such sharing is strictly for learning and development purposes only. The Gambit does not authorize or recommend the use of this report for formal grading, hiring, promotion, or performance evaluation.',
  },
  {
    title: '6. Data Protection & Privacy',
    body: 'Personal and assessment data will be used only for program delivery, reporting, and improvement. Data will not be sold or shared with unauthorized third parties. Access is restricted to authorized personnel and relevant stakeholders (where applicable). Reasonable measures will be taken to protect stored data. You may request access to or deletion of your data, subject to legal and operational requirements.',
  },
  {
    title: '7. Use of AI in the Experience (No Human Review)',
    body: "The Gambit uses AI-driven systems for:",
    list: [
      'Scenario generation',
      'Response analysis',
      'Report creation',
    ],
    footer:
      'All outputs are fully generated by automated systems without human review. Outputs are algorithmic interpretations based on participant inputs and predefined frameworks. They may contain errors, omissions, biases, or inaccuracies. Insights are indicative and exploratory, not verified conclusions.',
  },
  {
    title: '8. Confidentiality',
    body: 'Participants agree not to disclose or share:',
    list: [
      "Other participants' responses or behaviors.",
      'Simulation content, discussions, or scenarios.',
    ],
  },
  {
    title: '9. Intellectual Property',
    body: 'All materials, frameworks, scenarios, and methodologies are proprietary. Recording, copying, distributing, or recreating the experience without written permission is prohibited.',
  },
  {
    title: '10. Code of Conduct',
    body: "Participants must engage respectfully and professionally. The Gambit reserves the right to remove participants for inappropriate or disruptive behavior.",
  },
  {
    title: '11. Emotional & Psychological Acknowledgment',
    body: 'Participants acknowledge that:',
    list: [
      'The simulation may involve stress, pressure, or discomfort.',
      'Participation is at their own discretion.',
      'They may pause or withdraw at any time.',
    ],
  },
  {
    title: '12. No Professional Advice',
    body: 'This experience does not constitute psychological, medical, legal, financial, or career advice.',
  },
  {
    title: '13. Limitation of Liability',
    body: "To the maximum extent permitted by law: The Gambit and its facilitators shall not be liable for any direct, indirect, incidental, or consequential loss, damage, or impact arising from participation in the simulation or use of its outputs. All actions taken based on the insights provided are the sole responsibility of the participant or organization.",
  },
  {
    title: '14. Indemnification',
    body: "Participants and sponsoring organizations agree to indemnify and hold harmless The Gambit from any claims, damages, or liabilities arising from:",
    list: [
      'Participation in the program.',
      'Use or misuse of outputs or reports.',
      'Decisions made based on the insights provided.',
    ],
  },
  {
    title: '15. Minor Participation (if applicable)',
    list: [
      'Participants under the age of 18 must have consent from a parent or legal guardian.',
      'The guardian agrees to these terms on behalf of the participant.',
    ],
  },
  {
    title: '16. Governing Law',
    body: 'These terms shall be governed by the laws of the State of Florida, United States.',
  },
  {
    title: '17. Consent Acknowledgment',
    body: 'By participating, you confirm that:',
    list: [
      'You have read and understood these terms.',
      'You voluntarily agree to participate.',
      'You consent to data usage and report sharing as described above.',
    ],
  },
]

const SECTION_B = [
  {
    title: '1. Nature of the Report',
    body: 'This report reflects observed behavioral tendencies within a specific simulation context. It is not a standardized, scientific, or diagnostic assessment.',
  },
  {
    title: '2. Developmental Use Only',
    body: 'This report is intended solely for learning and development purposes. It must not be used as the sole basis for:',
    list: [
      'Academic grading',
      'Hiring decisions',
      'Promotions or role assignments',
      'Performance evaluations',
    ],
  },
  {
    title: '3. Context-Specific Interpretation',
    body: 'Results are influenced by:',
    list: ['Scenario design', 'Time pressure', 'Available information'],
    footer: 'Behavior may differ significantly in real-world environments.',
  },
  {
    title: '4. Indicative Insights Only',
    body: "The report highlights tendencies, not fixed abilities. It does not represent the participant's full capability or potential.",
  },
  {
    title: '5. AI-Generated Output (No Human Validation)',
    body: 'This report is generated entirely through AI-based systems without human validation.',
    list: [
      'Insights are interpretative and non-verified.',
      'Outputs may include biases, inaccuracies, or incomplete analysis.',
      'The report should not be treated as factual, diagnostic, or authoritative.',
    ],
  },
  {
    title: '6. Subjectivity of Evaluation',
    body: 'Results are based on algorithmic interpretation and predefined frameworks. They are not fully objective or comprehensive.',
  },
  {
    title: '7. Organizational Use Disclaimer',
    body: 'If shared with an institution or employer:',
    list: [
      'The report is intended only for development discussions.',
      'It must be combined with other evaluation methods and professional judgment.',
      "The Gambit is not responsible for decisions made by third parties using this report.",
    ],
  },
  {
    title: '8. Limitation of Liability',
    body: "The Gambit shall not be liable for any decisions, actions, or outcomes arising from the use or interpretation of this report.",
  },
  {
    title: '9. Confidentiality & Use',
    body: 'This report is confidential and intended only for:',
    list: [
      'The participant',
      'Authorized stakeholders (if applicable)',
    ],
    footer:
      'Unauthorized sharing, misrepresentation, or commercial use is prohibited.',
  },
  {
    title: '10. Intellectual Property',
    body: 'All report formats, frameworks, and methodologies are proprietary. Reproduction or distribution without permission is not allowed.',
  },
  {
    title: '11. Final Note',
    body: 'This report is a reflection of how you responded under pressure. It is not a definition of who you are or what you can become.',
  },
]

// ─── Helpers ────────────────────────────────────────────────────────────────

interface SectionItem {
  title: string
  body?: string
  list?: string[]
  footer?: string
}

function TermsSection({ item }: { item: SectionItem }) {
  return (
    <div className="space-y-2.5">
      <h3
        className="text-sm font-semibold text-[color:var(--color-warroom-ivory)] tracking-[0.02em]"
        style={{ fontFamily: 'var(--font-display)' }}
      >
        {item.title}
      </h3>
      {item.body && (
        <p
          className="text-sm text-[color:var(--color-warroom-smoke)] leading-relaxed"
          style={{ fontFamily: 'var(--font-body, serif)' }}
        >
          {item.body}
        </p>
      )}
      {item.list && (
        <ul className="space-y-1.5 pl-5">
          {item.list.map((li, i) => (
            <li
              key={i}
              className="text-sm text-[color:var(--color-warroom-smoke)] leading-relaxed list-disc marker:text-[color:var(--color-warroom-gold)]/40"
              style={{ fontFamily: 'var(--font-body, serif)' }}
            >
              {li}
            </li>
          ))}
        </ul>
      )}
      {item.footer && (
        <p
          className="text-sm text-[color:var(--color-warroom-smoke)] leading-relaxed font-medium"
          style={{ fontFamily: 'var(--font-body, serif)' }}
        >
          {item.footer}
        </p>
      )}
    </div>
  )
}

// ─── Page ───────────────────────────────────────────────────────────────────

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-[color:var(--color-warroom-void)]">
      {/* Atmospheric glow */}
      <div
        className="fixed inset-0 pointer-events-none"
        style={{
          background:
            'radial-gradient(ellipse at 50% 0%, var(--color-warroom-gold)/0.03 0%, transparent 60%)',
        }}
      />

      <div className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-16">
        {/* Back link — returns to the previous page (e.g. register), not always home */}
        <TermsBackLink />

        {/* Header */}
        <header className="mb-10">
          <div className="flex items-center gap-3 mb-3">
            <ScrollText className="h-6 w-6 text-[color:var(--color-warroom-gold)]" />
            <h1
              className="text-2xl font-bold tracking-[0.04em]"
              style={{
                fontFamily: 'var(--font-display)',
                background:
                  'linear-gradient(135deg, var(--color-warroom-gold), var(--color-warroom-gold-bright))',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
The Rules of Play
            </h1>
          </div>
          <p
            className="text-sm text-[color:var(--color-warroom-smoke)]"
            style={{ fontFamily: 'var(--font-body, serif)' }}
          >
            The Gambit — Terms & Conditions
          </p>
          {/* Divider */}
          <div className="mt-6 h-px bg-gradient-to-r from-transparent via-[color:var(--color-warroom-gold)]/30 to-transparent" />
        </header>

        {/* ═══ Section A ═══ */}
        <section className="mb-12">
          <div className="flex items-center gap-2.5 mb-6">
            <Shield className="h-5 w-5 text-[color:var(--color-warroom-gold)]" />
            <h2
              className="text-base font-semibold text-[color:var(--color-warroom-gold)] tracking-[0.04em]"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              A. Before Entering the Gambit
            </h2>
          </div>
          <p
            className="text-[10px] uppercase tracking-[0.14em] text-[color:var(--color-warroom-smoke)] mb-6"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Participant Agreement
          </p>

          <div className="space-y-6 pl-2 border-l border-[color:var(--color-warroom-gold)]/15">
            <div className="pl-5 space-y-6">
              {SECTION_A.map((item) => (
                <TermsSection key={item.title} item={item} />
              ))}
            </div>
          </div>
        </section>

        {/* Section divider */}
        <div className="my-10 h-px bg-gradient-to-r from-transparent via-[color:var(--color-warroom-gold)]/25 to-transparent" />

        {/* ═══ Section B ═══ */}
        <section className="mb-12">
          <div className="flex items-center gap-2.5 mb-6">
            <ScrollText className="h-5 w-5 text-[color:var(--color-warroom-gold)]" />
            <h2
              className="text-base font-semibold text-[color:var(--color-warroom-gold)] tracking-[0.04em]"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              B. THE GAMBIT Evaluation Report
            </h2>
          </div>
          <p
            className="text-[10px] uppercase tracking-[0.14em] text-[color:var(--color-warroom-smoke)] mb-6"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Terms and Conditions
          </p>

          <div className="space-y-6 pl-2 border-l border-[color:var(--color-warroom-gold)]/15">
            <div className="pl-5 space-y-6">
              {SECTION_B.map((item) => (
                <TermsSection key={item.title} item={item} />
              ))}
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="text-center pt-6 border-t border-[color:var(--color-warroom-ash)]/20">
          <p
            className="text-[10px] uppercase tracking-[0.16em] text-[color:var(--color-warroom-smoke)]"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            By entering the Gambit, you accept these terms in full.
          </p>
        </footer>
      </div>
    </div>
  )
}
